const Constants = {
    LOGGER_COLUMNS_AMOUNT: '3',
    LOGGER_INDEX_COLUMN_ID: '0',
    LOGGER_DATA_COLUMN_ID: '1',
    LOGGER_STAMP_COLUMN_ID: '3',
    LOGGER_INDEX_COLUMN_WIDTH: '100',
    LOGGER_DATA_COLUMN_WIDTH: '800',
    LOGGER_STAMP_COLUMN_WIDTH: '100',
    LOGGER_ROW_HEIGHT: '10'
};


export default Constants;
